server.port=5000
aws.region=ap-south-1
aws.dynamodb.table=ExpenseTable
aws.s3.bucket=expense-receipts
aws.sns.topicArn=arn:aws:sns:ap-south-1:ACCOUNT_ID:expense-alerts
#aws.endpointOverride=http://localhost:4566
